# Generated by Django 4.0.3 on 2022-04-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='mainapp/static/mainapp/img/products', verbose_name='image'),
        ),
    ]
